# Generated by Django 6.0.1 on 2026-04-03 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_admin', '0006_remove_activites_coordonnees_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMAIL_MESSAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.TextField()),
                ('cc', models.TextField(blank=True, default='')),
                ('bcc', models.TextField(blank=True, default='')),
                ('sujet', models.CharField(default='(Sans objet)', max_length=500)),
                ('corps', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé')], default='draft', max_length=10)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='email_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
