# Generated by Django 6.0.1 on 2026-04-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_admin', '0007_add_email_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMAIL_MESSAGE',
        ),
    ]
