# Generated by Django 6.0.1 on 2026-04-03 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_admin', '0008_remove_email_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('sent', 'Envoyé'), ('received', 'Reçu')], default='sent', max_length=10)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_emails', models.TextField(default='[]')),
                ('cc_emails', models.TextField(blank=True, default='[]')),
                ('bcc_emails', models.TextField(blank=True, default='[]')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'direction', 'is_deleted'], name='cluster_adm_user_id_0361f0_idx'), models.Index(fields=['user', 'is_starred'], name='cluster_adm_user_id_f2d507_idx')],
            },
        ),
    ]
