# Generated by Django 6.0.1 on 2026-04-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_admin', '0010_alter_emaillog_direction_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='projets',
            name='budjets',
            field=models.IntegerField(default=0),
        ),
    ]
