# Generated by Django 6.0.1 on 2026-04-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_admin', '0011_projets_budjets'),
    ]

    operations = [
        migrations.AddField(
            model_name='activites',
            name='Femme',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activites',
            name='Homme',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activites',
            name='Nbre_de_beneficiaires',
            field=models.IntegerField(default=0),
        ),
    ]
