# Generated by Django 6.0.1 on 2026-04-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_admin', '0012_activites_femme_activites_homme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activites',
            name='Type_activites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cluster_admin.type_activites'),
        ),
    ]
