# Generated by Django 6.0.1 on 2026-04-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_admin', '0013_activites_type_activites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activites',
            name='tonnage',
        ),
    ]
