# Generated by Django 6.0.1 on 2026-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_admin', '0014_remove_activites_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projets',
            name='Budgets',
            field=models.IntegerField(default=0),
        ),
    ]
